### ISSUE TITLE
Change protocol registration from HKEY_CLASSES_ROOT to HKEY_CURRENT_USER

### ISSUE THREAD

**Issue by scheid-beni** [miyako/4d-plugin-custom-url-scheme#1]
## Description
Currently, the protocol registration in `4DPlugin-Protocol.cpp` requires administrator privileges because it writes to HKEY_CLASSES_ROOT and HKEY_LOCAL_MACHINE. This creates unnecessary security requirements and potential deployment issues.

### Current Behavior
- Protocol is registered in `HKEY_CLASSES_ROOT`
- IE security settings are written to `HKEY_LOCAL_MACHINE`
- Requires administrator privileges to run
- May fail silently if user doesn't have admin rights

### Proposed Changes
Change registry operations to use `HKEY_CURRENT_USER` instead:
1. Replace `HKEY_CLASSES_ROOT` with `HKEY_CURRENT_USER\SOFTWARE\Classes`
2. Replace `HKEY_LOCAL_MACHINE` with `HKEY_CURRENT_USER` for IE security settings

### Benefits
- No administrator privileges required
- Follows Windows best practices for per-user protocol handlers
- Still maintains full protocol handler functionality

### Code Example
<code>
// Change from:
LONG err = RegCreateKeyEx(HKEY_CLASSES_ROOT,
scheme.c_str(),
...);
// To:
std::wstring keyPath = L"SOFTWARE\\Classes\\" + scheme;
LONG err = RegCreateKeyEx(HKEY_CURRENT_USER,
keyPath.c_str(),
</code>

### References
- [Microsoft Docs: Application Registration](https://docs.microsoft.com/en-us/windows/win32/shell/app-registration)
- [[HKEY_LOCAL_MACHINE\SOFTWARE\Classes vs HKEY_CLASSES_ROOT](https://stackoverflow.com/questions/53984433/hkey-local-machine-software-classes-vs-hkey-classes-root)](https://stackoverflow.com/questions/53984433/hkey-local-machine-software-classes-vs-hkey-classes-root)

**Comment by miyako** [comment]
thank you for the practical suggestion!
I've made the necessary changes in [1.1.0](https://github.com/miyako/4d-plugin-custom-url-scheme/releases/tag/1.1.0).
